version: '3.7'
services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend/
      - /var/run/docker.sock:/var/run/docker.sock
    command: bash -c "sleep 3 && psql -h db -U postgres -w -f ./app/db/db_dump.sql && (uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000 & sleep 4 && pytest ./tests/)"
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    ports:
      - 5433:5432
volumes:
    postgres_data: